name: Run Python Script and Commit Output

on:
  schedule:
    # Run every day at 9:00 PM UTC
    - cron: '*/2 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
        # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run script
        run: python dish.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git add *.json
          git commit -m "Update generated JSON file [skip ci]"
          git push
        env:
          # Use a personal access token to push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
